"""Climate-related sensor entity descriptions."""

from __future__ import annotations

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)

ENTITY_CLIMATE_DESCRIPTIONS = (
    SensorEntityDescription(
        key="air_blower_active",
        translation_key="air_blower_active",
        name="Air blower active",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="cds_climate_active",
        translation_key="cds_climate_active",
        name="CDS climate active",
        icon="mdi:snowflake",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="climate_over_heat_protection_active",
        translation_key="climate_over_heat_protection_active",
        name="Climate over heat protection active",
        icon="mdi:thermostat",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="curtain_open_status",
        translation_key="curtain_open_status",
        name="Curtain open status",
        icon="mdi:curtains",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="defrosting_active",
        translation_key="defrosting_active",
        name="Defrosting active",
        icon="mdi:snowflake",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="driver_heating_detail",
        translation_key="driver_heating_detail",
        name="Driver heating detail",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="driver_heating_status",
        translation_key="driver_heating_status",
        name="Driver heating status",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="driver_ventilation_detail",
        translation_key="driver_ventilation_detail",
        name="Driver ventilation detail",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="driver_ventilation_status",
        translation_key="driver_ventilation_status",
        name="Driver ventilation status",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="exterior_temperature",
        translation_key="exterior_temperature",
        name="Exterior temperature",
        icon="mdi:home-thermometer-outline",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="frag_active",
        translation_key="frag_active",
        name="FRAG active",
        icon="mdi:chat-question-outline",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="interior_temperature",
        translation_key="interior_temperature",
        name="Interior temperature",
        icon="mdi:thermometer",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="passenger_heating_detail",
        translation_key="passenger_heating_detail",
        name="Passenger heating detail",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="passenger_heating_status",
        translation_key="passenger_heating_status",
        name="Passenger heating status",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="passenger_ventilation_detail",
        translation_key="passenger_ventilation_detail",
        name="Passenger ventilation detail",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="passenger_ventilation_status",
        translation_key="passenger_ventilation_status",
        name="Passenger ventilation status",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="pre_climate_active",
        translation_key="pre_climate_active",
        name="Pre climate active",
        icon="mdi:heat-pump-outline",
    ),
    SensorEntityDescription(
        key="rear_left_heating_detail",
        translation_key="rear_left_heating_detail",
        name="Rear left heating detail",
        icon="mdi:heat-pump-outline",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="rear_left_heating_status",
        translation_key="rear_left_heating_status",
        name="Rear left heating status",
        icon="mdi:heat-pump-outline",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="rear_left_ventilation_detail",
        translation_key="rear_left_ventilation_detail",
        name="Rear left ventilation detail",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="rear_left_ventilation_status",
        translation_key="rear_left_ventilation_status",
        name="Rear left ventilation status",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="rear_right_heating_detail",
        translation_key="rear_right_heating_detail",
        name="Rear right heating detail",
        icon="mdi:heat-pump-outline",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="rear_right_heating_status",
        translation_key="rear_right_heating_status",
        name="Rear right heating status",
        icon="mdi:heat-pump-outline",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="rear_right_ventilation_detail",
        translation_key="rear_right_ventilation_detail",
        name="Rear right ventilation detail",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="rear_right_ventilation_status",
        translation_key="rear_right_ventilation_status",
        name="Rear right ventilation status",
        icon="mdi:fan",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="steering_wheel_heating_status",
        translation_key="steering_wheel_heating_status",
        name="Steering wheel heating status",
        icon="mdi:steering",
    ),
    SensorEntityDescription(
        key="sun_curtain_rear_open_status",
        translation_key="sun_curtain_rear_open_status",
        name="Sun curtain rear open status",
        icon="mdi:curtains",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="sun_curtain_rear_position",
        translation_key="sun_curtain_rear_position",
        name="Sun curtain rear position",
        icon="mdi:curtains",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="sunroof_open_status",
        translation_key="sunroof_open_status",
        name="Sunroof open status",
        icon="mdi:window-shutter",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="sunroof_position",
        translation_key="sunroof_position",
        name="Sunroof position",
        icon="mdi:window-shutter",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="window_driver_position",
        translation_key="window_driver_position",
        name="Window driver position",
        icon="mdi:window-open",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="window_driver_rear_position",
        translation_key="window_driver_rear_position",
        name="Window driver rear position",
        icon="mdi:window-open",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="window_passenger_position",
        translation_key="window_passenger_position",
        name="Window passenger position",
        icon="mdi:window-open",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="window_passenger_rear_position",
        translation_key="window_passenger_rear_position",
        name="Window passenger rear position",
        icon="mdi:window-open",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="window_driver_status",
        translation_key="window_driver_status",
        name="Window driver status",
        icon="mdi:window-open",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="window_driver_rear_status",
        translation_key="window_driver_rear_status",
        name="Window driver rear status",
        icon="mdi:window-open",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="window_passenger_status",
        translation_key="window_passenger_status",
        name="Window passenger status",
        icon="mdi:window-open",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="window_passenger_rear_status",
        translation_key="window_passenger_rear_status",
        name="Window passenger rear status",
        icon="mdi:window-open",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="interior_PM25",
        translation_key="interior_pm25",
        name="Interior PM25",
        icon="mdi:air-filter",
        entity_registry_enabled_default=False,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="relative_humidity",
        translation_key="relative_humidity",
        name="Relative humidity",
        icon="mdi:water-percent",
        device_class=SensorDeviceClass.HUMIDITY,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="%",
        entity_registry_enabled_default=False,
    ),
)
