"""Running-related sensor entity descriptions."""

from __future__ import annotations

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)

ENTITY_RUNNING_DESCRIPTIONS = (
    SensorEntityDescription(
        key="ahbc_status",
        translation_key="ahbc_status",
        name="Adaptive high beam control",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="goodbye",
        translation_key="goodbye",
        name="Goodbye Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="home_safe",
        translation_key="home_safe",
        name="Home Safe Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="corner_light",
        translation_key="corner_light",
        name="Corner Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="front_fog_light",
        translation_key="front_fog_light",
        name="Front Fog Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="stop_light",
        translation_key="stop_light",
        name="Stop Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="trip_meter1",
        translation_key="trip_meter1",
        name="Trip meter 1",
        icon="mdi:counter",
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="km",
    ),
    SensorEntityDescription(
        key="trip_meter2",
        translation_key="trip_meter2",
        name="Trip meter 2",
        icon="mdi:counter",
        device_class=SensorDeviceClass.DISTANCE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="km",
    ),
    SensorEntityDescription(
        key="approach",
        translation_key="approach",
        name="Approach Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="high_beam",
        translation_key="high_beam",
        name="High Beam Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="engine_coolant_level_status",
        translation_key="engine_coolant_level_status",
        name="Engine coolant level status",
        icon="mdi:car-coolant-level",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="low_beam",
        translation_key="low_beam",
        name="Low Beam Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="position_light_rear",
        translation_key="position_light_rear",
        name="Position Light Rear",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="light_show",
        translation_key="light_show",
        name="Light Show",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="welcome",
        translation_key="welcome",
        name="Welcome Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="drl",
        translation_key="drl",
        name="Daytime running light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="ahl",
        translation_key="ahl",
        name="Adaptive headlight",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="trun_indicator_left",
        translation_key="turn_indicator_left",
        name="Turn indicator left",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="trun_indicator_right",
        translation_key="turn_indicator_right",
        name="Turn indicator right",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="adaptive_front_light",
        translation_key="adaptive_front_light",
        name="Adaptive front light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="dbl",
        translation_key="dbl",
        name="Double Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="average_speed",
        translation_key="average_speed",
        name="Average speed",
        icon="mdi:speedometer",
        device_class=SensorDeviceClass.SPEED,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="km/h",
    ),
    SensorEntityDescription(
        key="position_light_front",
        translation_key="position_light_front",
        name="Position Light Front",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="reverse_light",
        translation_key="reverse_light",
        name="Reverse Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="highway_light",
        translation_key="highway_light",
        name="Highway Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="rear_fog_light",
        translation_key="rear_fog_light",
        name="Rear Fog Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="flash_light",
        translation_key="flash_light",
        name="Flash Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
    SensorEntityDescription(
        key="all_weather_light",
        translation_key="all_weather_light",
        name="All Weather Light",
        icon="mdi:car-parking-lights",
        entity_registry_enabled_default=False,
    ),
)
